name: Metrics
on:
  workflow_dispatch:
  push: {
    branches: ["master", "main"]
  }
  schedule:
    - cron: '* * * * *'
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_introduction: yes
          plugin_introduction_title: no
          plugin_achievements: yes
          plugin_achievements_threshold: X
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0
          plugin_traffic: yes
          plugin_languages: yes
          plugin_languages_ignored: SVG
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_threshold: 0%
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming, data, prose
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 7
          commits_authoring: ["ba004745@bac.qld.edu.au", "pradolifu@gmail.com"]
